services:
  - type: web
    name: readersdot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn readersdot.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: readersdot.settings
      - key: PYTHON_VERSION
        value: 3.10
    staticPublishPath: staticfiles