# Generated by Django 5.2.1 on 2025-05-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
